### ISSUE TITLE
PyLag fails to build with cython >= 3.0.1

### ISSUE THREAD

**Issue by jimc101** [pmlmodelling/pylag#128]
It fails because there is a typo in the `create_fvcom_grid_metrics_file` function definition. The central latitude argument should be of type float, not int. Ultimately, an attribute error is thrown when grid_metrics.pyx is processed:

```
AttributeError: 'NoneType' object has no attribute 'cname'
```
